name: Java Katas Testing

on:
  push:
    branches:
      - main
    paths:
      - 'Java/**'

defaults:
  run:
    working-directory: ./Java

jobs:
  test:
    name: Run Katas tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run tests
        run: mvn clean test --batch-mode
